### ISSUE TITLE
feature parity with official cnto template r0b10

### ISSUE THREAD

**Issue by freghar** [CntoDev/template#11]
- [x] moving spawned units under server (#4)
- [x] taw_vd in a mod (#1)
- [x] placed unit/modules as a `.sqm` mission OR unit/module compositions
- [x] main loadout system (Units addon CntoDev/mods#1), currently F3
  - class-based loadouts for now, Units addon long-term
- [x] solution to renaming groups for BFT (currently F3) - possibly vanilla Callsign module
  - Callsign module doesn't work on dedicated, use `this setGroupId ["A1"];` in init field
- [x] how to do briefings (currently F3 module)
  - F5 (Systems) → Modules → Intel → Create Diary Record
- [x] "buddy team" colors on mission start, currently F3
  - may use `this assignTeam "RED";` in init field
- [x] AI skill settings (`f_setAISkill.sqf`?)
  - will use ASR AI settings + vanilla skill adjustment / MCC
- [x] freezing players on mission start for X seconds (alternative to F3 bullet removal)
  - freezing not easily possible, bullet removal replaced with [safe zone](https://forums.bistudio.com/topic/129592-base-protection-script/) "building"
- [x] alt loadout system (arsenal / faction-based files)
- [ ] per-type (Coop/PvP/Training/..) template customizations
  - [ ] branding, logos, etc.
  - [ ] type-specific `init.sqf` content (ie. training ranges load, MCC/TAW pvp disablement)
- [x] PvP spectator mode, currently seems to be F3 spectator
  - will use vanilla spectator
- [ ] PvP timed mission start
- [ ] mod-specifics outside `mission.sqm`
  - [ ] ACRE2 configuration sections
