### ISSUE TITLE
Ares_Extras todo / wishlist

### ISSUE THREAD

**Issue by freghar** [CntoDev/template#14]
- [x] toggling IR lasers / weapon flashlights, with the option of adding IR/flash if unit doesn't have one (or removing it)
- [x] somewhat persistent lights on vehicles/helicopters, even when unit isn't `SAFE` - either via `disableAI` or scheduled loop, enabling it on every frame :(
- [x] allowCrewInImmobile
- [x] test + implement wrapper for `setUnloadInCombat`
- [ ] offroad modification
  - [ ] [colors and features](https://forums.bistudio.com/topic/147049-setting-color-of-offroad/?p=2349257)
  - [ ] [police/utility lights](https://forums.bistudio.com/topic/147049-setting-color-of-offroad/?p=2397360) - needs modification, use `attachTo` (doesn't jitter), optimization, sync with `_this animate ["BeaconsStart", 1];`, use generic `functions/Lights/*` and only call it from Ares
- [ ] setSpeciality / setUnitTrait (1.58), hopefully with [hidden functionality](https://forums.bistudio.com/topic/150500-development-branch-captains-ai-log/?p=2989127) (camouflage/audible/..)
- [ ] improve fn_haulAss, experiment with target disassociation
  - https://forums.bistudio.com/topic/150499-ai-discussion-dev-branch/?p=3013889
- [x] make AI unit(s) sit down, just call fn_sitDown, improve it to not call AI functions / loop for player units
- `enableAI` / `disableAI` with a dialog of all features? - bad idea considering how buggy it can get
- `flyInHeight` - no need, Curator-dragged height level works, maybe new `flyInHeightASL`?
- [x] align objects to terrain vector - fix MCC load
- [ ] captive setting - make enemy AI temporarily /friendly/
- [ ] AI suppression fire on area (1.60 overhaul)
- [ ] smooth weather transitions ([overcast](https://community.bistudio.com/wiki/setOvercast), [fog](https://community.bistudio.com/wiki/setFog), [rainbow](https://community.bistudio.com/wiki/setRainbow), [windDir](https://community.bistudio.com/wiki/setWindDir), [setWindForce](https://community.bistudio.com/wiki/setWindForce), [setWindStr](https://community.bistudio.com/wiki/setWindStr), [setRain](https://community.bistudio.com/wiki/setRain), [setWaves](https://community.bistudio.com/wiki/setWaves), [setLightnings](https://community.bistudio.com/wiki/setLightnings), [setGusts](https://community.bistudio.com/wiki/setGusts)) coupled with info that only one change at a time is possible + time to end from `nextWeatherChange`
- [x] animation reset (ie. after being crushed in `allowDamage false`):  `_unit switchMove "";`
- [ ] [FULL arsenal](https://github.com/astruyk/Ares/issues/209#issuecomment-180609294), incl. faces / voices, so the Export button works

...
- [ ] move Ares_Extras to a mod, it's getting too big + is client-side only
